### ISSUE TITLE
Incompatible RID on Darwin

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/PlatformAbstractions#23] opened 2016-03-01 01:57 UTC
On our travis builds I'm seeing failures with the message (https://travis-ci.org/aspnet/PlatformAbstractions/jobs/112436248): 
`error: System.Console 4.0.0-rc2-23819 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.`

Which osx rids are supported?

cc @anurse

**Comment by anurse** [comment] 2016-03-01 16:47
You need to change to a travis image that uses `10.10` or higher. /cc @BrennanConroy

**Comment by moozzyk** [comment] 2016-03-01 16:48
Was it working because previously we were able to override the RID using an env variable? Isn't it available in dotnet cli?

**Comment by BrennanConroy** [comment] 2016-03-01 16:51
Look at the other .travis files e.g. https://github.com/aspnet/Logging/blob/dev/.travis.yml#L18

**Comment by anurse** [comment] 2016-03-01 16:51
I'm pretty sure @BrennanConroy fixed it by just changing our Travis image. Re-opening now that I see that the issue is actually in PlatformAbstractions' travis.yml (Brennan beat me to it). I thought this was a general RID problem :)

The fix for this is to set the right Travis image, and @BrennanConroy has the details.

@moozzyk I believe we still have the env var, but that's a secondary issue.

**Comment by anurse** [comment] 2016-03-01 16:53
Confirmed we have the env var: https://github.com/aspnet/PlatformAbstractions/blob/dev/src/Microsoft.Extensions.PlatformAbstractions/RuntimeEnvironmentExtensions.cs#L7

**Comment by moozzyk** [comment] 2016-03-01 17:22
OK. I didn't know `xcode7.1` means `osx.10.10`

**Closed** 2016-03-02 00:18 UTC
